[cursor.style]
shape = "Underline"
blinking = "Always"

[cursor]
unfocused_hollow = false

[font]
size = 12

[font.normal]
family = "Jet Brains Mono Nerd Font"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window.padding]
x = 5
y = 5

[shell]
program = "/usr/bin/zsh"

[window]
opacity = 0.8
#blur = true
